<a href="https://colab.research.google.com/github/logsdail/external_examples/blob/master/notebooks/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.random.random((3,3))
print (a.strides)
print (a)
print (a.flags)

(24, 8)
[[0.83305468 0.72443056 0.7390224 ]
 [0.7636519  0.41924702 0.12148417]
 [0.49325928 0.76637842 0.04579925]]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [ ]:
# Creating views
b = a[1:, ::]
print (b)
print (b.flags)
print (b.base)

[[0.7636519  0.41924702 0.12148417]
 [0.49325928 0.76637842 0.04579925]]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

[[0.83305468 0.72443056 0.7390224 ]
 [0.7636519  0.41924702 0.12148417]
 [0.49325928 0.76637842 0.04579925]]


In [ ]:
b [0, 0] = 0
print (a)

[[0.83305468 0.72443056 0.7390224 ]
 [0.         0.41924702 0.12148417]
 [0.49325928 0.76637842 0.04579925]]


### Advanced indexing

In [ ]:
a = np.random.random(9)
print (a.flags)
print (a.strides)


  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

(8,)


In [ ]:
b = a[2:8:-2]
print (b.flags)
print (b.strides)
print (b.base is None)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

(8,)
False


In [ ]:
b = a[ [2,2,5,2,3] ]
print (b.flags)
print (b.strides)
print (b.base is None)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

(8,)
True


In [ ]:
b = a[np.newaxis, :, np.newaxis]
print (b.shape)
print (b.flags)
print (b.strides)
print (b.base is None)

(1, 9, 1)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

(0, 8, 0)
False


### uFuncs

In [ ]:
a = np.array([1,2,3])
b = np.array([3,2,1])
print(a + b)
print(a ** b)
print(np.exp(a))

[4 4 4]
[1 4 3]
[ 2.71828183  7.3890561  20.08553692]


In [ ]:
a = np.arange(9).reshape((3,3))
b = np.random.random((3,3))

a + b


array([[0.83765215, 1.23205061, 2.52749184],
       [3.04259634, 4.06560744, 5.69208598],
       [6.67867256, 7.15571002, 8.25359563]])

###Broadcasting

In [ ]:
a = np.arange(9).reshape((3,3))
b = np.array([10, 20, 30, 40])
a + b


ValueError: ignored

In [ ]:
# From rigth to left:
a = np.arange(9).reshape((3,3))
b = np.array([10, 20, 30])
print (a.shape, b.shape)
print (a)
print (b)
c = a + b
print (c.shape)
print (c)

(3, 3) (3,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[10 20 30]
(3, 3)
[[10 21 32]
 [13 24 35]
 [16 27 38]]


In [ ]:
bT = b.T
print(bT.shape)
d = a + bT
print (d)

(3,)
[[10 21 32]
 [13 24 35]
 [16 27 38]]


In [ ]:
bT = b[:, np.newaxis]
print(bT.shape)
d = a + bT
print (d)

(3, 1)
[[10 11 12]
 [23 24 25]
 [36 37 38]]


In [ ]:
x = np.arange(3)
y = np.arange(4) * 10
xv, yv = np.meshgrid(x, y, copy=False, indexing='ij')
print (xv.shape, yv.shape)
print (xv)
print (yv)


(3, 4) (3, 4)
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]
[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [ ]:
xv[0,0] = 999
print (xv)

[[999 999 999 999]
 [  1   1   1   1]
 [  2   2   2   2]]


In [ ]:
# strides trick as copy=False
print (xv.strides, yv.strides)
print (xv.flags)
print ("Assign 9:")
xv[0,0] = 9
print (xv)

(8, 0) (0, 8)
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

Assign 9:
[[9 9 9 9]
 [1 1 1 1]
 [2 2 2 2]]


In [ ]:
x =np.arange(3)
xv = x[:, np.newaxis]
print (xv)
print (xv.shape)
print (xv.strides)

xvv = np.lib.stride_tricks.as_strided(xv, shape=(3,4), strides=xv.strides)
print (xvv)
print (xvv.shape)
print (xvv.strides)
xvv[0,0] = 999
print (x)

[[0]
 [1]
 [2]]
(3, 1)
(8, 0)
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]
(3, 4)
(8, 0)
[999   1   2]


### Outer method

In [ ]:
x = np.arange(3)
y = np.arange(4) * 10
np.add.outer(x,y)
np.multiply.outer(x,y)

array([[ 0, 10, 20, 30],
       [ 1, 11, 21, 31],
       [ 2, 12, 22, 32]])

### Reduction


In [ ]:
t = np.random.random((10, 2, 3)) # trajectory[step, atom, coordinate]

print ("average position over time:", np.mean(t, axis = 0 ).shape)
print ("trajectory of the center of mass:", np.mean(t, axis = 1 ).shape)
print ("distances to the origin over time:", np.linalg.norm(t, axis = 2 ).shape)



average position over time: (2, 3)
trajectory of the center of mass: (10, 3)
distances to the origin over time: (10, 2)


In [ ]:
print(np.mean(t, axis = 0 ))
print( np.add.reduce(t, axis = 0) / t.shape[0]) 

[[0.33858068 0.4862304  0.43246406]
 [0.51373368 0.38522173 0.61884273]]
[[0.33858068 0.4862304  0.43246406]
 [0.51373368 0.38522173 0.61884273]]


In [ ]:
a1 = np.linalg.norm(t, axis = 2 )
a2 = np.add.reduce(t**2, axis = 2) ** 0.5
print (a1)
print (a2)

[[1.16780158 1.47328716]
 [0.82779632 0.959646  ]
 [1.0408013  0.97734402]
 [1.02345827 1.04891167]
 [0.55084593 1.38501892]
 [1.24378562 0.90277917]
 [0.63200693 1.3065471 ]
 [1.26174562 1.02385361]
 [0.92009422 0.42391272]
 [0.64273454 0.98212019]]
[[1.16780158 1.47328716]
 [0.82779632 0.959646  ]
 [1.0408013  0.97734402]
 [1.02345827 1.04891167]
 [0.55084593 1.38501892]
 [1.24378562 0.90277917]
 [0.63200693 1.3065471 ]
 [1.26174562 1.02385361]
 [0.92009422 0.42391272]
 [0.64273454 0.98212019]]


In [ ]:
np.testing.assert_allclose(a1, a2 + 1e-6, rtol=1e-5, atol=1e-5 )

In [ ]:
a = np.random.random(9)

b = []
for x in a:
  if  x > 10:
    b.append(x)



b = a[ a > 10 ]
